In [2]:
import tensorflow as tf

scalar = tf.constant(42)
print(scalar)


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

tf.Tensor(42, shape=(), dtype=int32)


2023-02-20 22:05:10.572876: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-02-20 22:05:10.573549: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
import tensorflow as tf

vector = tf.constant([1, 2, 3])
print(vector)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [4]:
import tensorflow as tf

matrix = tf.constant([[1, 2], [3, 4], [5, 6]])
print(matrix)


tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [5]:
import tensorflow as tf

image = tf.constant([
  [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
  [[255, 255, 0], [255, 0, 255], [0, 255, 255]],
  [[255, 255, 255], [0, 0, 0], [128, 128, 128]]])

print(image)

tf.Tensor(
[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [255   0 255]
  [  0 255 255]]

 [[255 255 255]
  [  0   0   0]
  [128 128 128]]], shape=(3, 3, 3), dtype=int32)


In [6]:
import tensorflow as tf

tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])
result = tensor1 + tensor2
print(result)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)
